### ISSUE TITLE
Change site description

### ISSUE THREAD

**Issue by tweinreich** [getgrav/grav-skeleton-mediator-site#1]
Hi,

First I have to thank you for creating this awesom skeleton for the first SSG, I actually want to use!

I have a question about how to change the site description. By changing Metadata/description (what is for SEO when I understand it correctly) I couldn't change the sites subtitle and after searching around I couldn't yet find a solution to do so.

Can anybody help me please? 

I added a picture to show you what I mean:
![grav_mediator_desc](https://cloud.githubusercontent.com/assets/4059641/10023567/17af778a-6153-11e5-82bf-4dadd1887bb4.png)

**Comment by flaviocopes** [comment]
Closing this - questions on forum, please
