### ISSUE TITLE
.dependencies not found

### ISSUE THREAD

**Issue by jault3** [getgrav/grav-skeleton-mediator-site#2]
I downloaded to most recent (v1.0.2) and I navigated to the root of the zip folder I extracted. I then ran `bin/grav install` and received the error message below. Looks like this file needs to be defined

```
ERROR Missing .dependencies file in user/ folder
ERROR invalid YAML in .dependencies
```

**Comment by flaviocopes** [comment]
You don't need to run `bin/grav install` on a Skeleton package you download from getgrav.org, as that already contains all the dependencies. You'd need to do that when downloading the code from Github directly (http://learn.getgrav.org/basics/installation#option-2-install-from-github)
